### ISSUE TITLE
Awesome stuff cxlso!

### ISSUE THREAD

**Issue by LoyWeiWin** [cxlso/MDPH2_on_UR10e#1]
Is any part of the components using C++?

**Comment by cxlso** [comment]
Hi Wei, thank you so much, I'm happy you like it!
I think it automatically mentioned C++ because of the Arduino code but there's no C++ in Grasshopper.
I'm thinking of including a screenshot of the GH definition so we don't need to open the file to see what's inside!
I'm new to GitHub I have to familiarize myself with all the settings 😊
